app:
  bot:
    botUsername: ${BOT_USERNAME}
    botToken: ${TOKEN_BOT}
    admin_id: ${ADMIN_ID}

  tutor-cases:
    cases:
      - id: 1
        image: ${IMAGE_CASE_1}
        description: >
          Ученица Татьяна очень успешна в учёбе, без труда справляется со всеми
          учебными задачами, однако на уроках часто отвлекается, мешает другим детям и т.д
        tasks:
          - "- Проанализируйте ситуацию, дайте ей оценку."
          - "- Определите, каковы причины подобного поведения ребёнка?"
          - "- Что необходимо предпринять педагогам класса для решения ситуации?"
      - id: 2
        image: ${IMAGE_CASE_2}
        description: >
          Мама (Татьяна Ивановна) обратилась в администрацию школы с жалобой по
          факту получения травмы её ребёнком… и т.д
        tasks:
          - "- Проанализируйте ситуацию, дайте ей оценку."
          - "- Определите пути взаимодействия всех участников образовательного процесса."
      - id: 3
        image: ${IMAGE_CASE_3}
        description: >
          В класс зачислен новый ученик Вася, который… и т.д.
        tasks:
          - "- Опишите первые шаги адаптации ученика."
          - "- Как организовать работу с родителями?"

spring:

  output:
    ansi:
      enabled: always

  config:
    import: optional:file:.env[.properties]

logging:
  config: classpath:logback-spring.xml