app:
  bot:
    botUsername: ${BOT_USERNAME}
    botToken: ${TOKEN_BOT}
    admin_id: ${ADMIN_ID}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  output:
    ansi:
      enabled: always

  config:
    import:
      - optional:file:.env[.properties]
      - optional:classpath:cases.yml

  cache:
    type: redis
    cache-names:
      - surveySessions
      - caseSessions
    redis:
      time-to-live: 2h

logging:
  config: classpath:logback-spring.xml
