app:
  bot:
    botUsername: ${BOT_USERNAME}
    botToken: ${TOKEN_BOT}
    admin_id: ${ADMIN_ID}

spring:

  output:
    ansi:
      enabled: always

  config:
    import:
      - optional:file:.env[.properties]
      - optional:classpath:cases.yml

logging:
  config: classpath:logback-spring.xml